name: SonarQube Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run SonarQube Scanner
        uses: SonarSource/sonarqube-scan-action@v1
        with:
          entryPoint: '/bin/bash'
          args: |
            -Dsonar.projectKey=react-pilot-test
            -Dsonar.projectName=React-Pilot-Test
            -Dsonar.sources=src
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
